set module_name clk_wiz_100mhz_au250

create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name $module_name -dir ${ip_build_dir}

set_property -dict [list \
  CONFIG.AUTO_PRIMITIVE {PLL} \
  CONFIG.CLKIN1_JITTER_PS {33.330000000000005} \
  CONFIG.CLKOUT1_DRIVES {Buffer} \
  CONFIG.CLKOUT1_JITTER {143.207} \
  CONFIG.CLKOUT1_PHASE_ERROR {114.212} \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100.000} \
  CONFIG.CLKOUT2_DRIVES {Buffer} \
  CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {300.000} \
  CONFIG.CLKOUT3_DRIVES {Buffer} \
  CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {300.000} \
  CONFIG.CLKOUT4_DRIVES {Buffer} \
  CONFIG.CLKOUT4_REQUESTED_OUT_FREQ {300.000} \
  CONFIG.CLKOUT5_DRIVES {Buffer} \
  CONFIG.CLKOUT5_REQUESTED_OUT_FREQ {300.000} \
  CONFIG.CLKOUT6_DRIVES {Buffer} \
  CONFIG.CLKOUT6_REQUESTED_OUT_FREQ {300.000} \
  CONFIG.CLKOUT7_DRIVES {Buffer} \
  CONFIG.CLKOUT7_REQUESTED_OUT_FREQ {300.000} \
  CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} \
  CONFIG.MMCM_BANDWIDTH {OPTIMIZED} \
  CONFIG.MMCM_CLKFBOUT_MULT_F {8} \
  CONFIG.MMCM_CLKIN1_PERIOD {3.333} \
  CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
  CONFIG.MMCM_CLKOUT0_DIVIDE_F {8} \
  CONFIG.MMCM_COMPENSATION {AUTO} \
  CONFIG.MMCM_DIVCLK_DIVIDE {3} \
  CONFIG.OPTIMIZE_CLOCKING_STRUCTURE_EN {true} \
  CONFIG.PRIMITIVE {Auto} \
  CONFIG.PRIM_IN_FREQ {300.000} \
  CONFIG.USE_FREQ_SYNTH {true} \
  CONFIG.USE_LOCKED {false} \
  CONFIG.USE_RESET {false} \
] [get_ips $module_name]
